name: blog
channels:
  - defaults
dependencies:
- docutils
- ipython
- markdown=2.6.11
- nbconvert
- openssl
- pip
- python=3.8
- python-dateutil
- pytz
- pyyaml
- readline
- requests
- setuptools
- six
- sqlite
- tk
- unidecode
- wheel
- xz
- yaml
- zlib
- pip:
  - blinker
  - feedgenerator
  - ghp-import
  - markupsafe
  - nbdime
  - pelican
  - pygments
# prefix: /home/daniel/miniconda/envs/blog
