name: Compile latest content and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  compile_and_deploy:
    name: Compile latest content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest materials
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install required packages
        run: |
          python --version
          pip install wheel
          pip install -r requirements.txt

      - name: Compile latest content
        run: |
          make html
          make publish
      
      # - name: Archive compiled content for deployment
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: built website content
      #     path: output/

      # - name: Retrieve compiled content
      #   uses: actions/download-artifact@master
      #   with:
      #     name: built website content
      #     path: output

      - name: Set up private key for deployment server
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Webfaction
        run: |
          make rsync_upload 