name: Compile latest content and deploy

on:
  push:
    branches: [ master ]

jobs:

  compile_and_deploy:
    name: Compile latest content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest materials
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install required packages
        run: |
          python --version
          pip install wheel
          pip install -r requirements.txt

      - name: Check working dir
        run: |
          echo $PWD
          ls -alh

      - name: Compile latest content
        run: |
          make html
          make publish
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa 

      - name: Deploy to Webfaction
        run: |
          make rsync_upload 